################################################################################
# Automatically-generated file. Do not edit!
################################################################################

I_SRCS := 
S_SRCS := 
ASM_UPPER_SRCS := 
CPCP_SRCS := 
ASM_SRCS := 
C_SRCS := 
MCS_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
I_DEPS := 
PCP_S := 
EXECUTABLES := 
OBJS := 
C_DEPS := 
CPCP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Src/AppSw/CpuGeneric/Config \
Src/AppSw/Tricore/Main \
Src/AppSw/Tricore/Timer \
Src/AppSw/Tricore/can \
Src/AppSw/Tricore/eru \
Src/AppSw/Tricore/gpio \
Src/AppSw/Tricore/spi \
Src/AppSw/Tricore/stm_systick \
Src/AppSw/Tricore/uart \
Src/BaseSw/Infra/Platform/Tricore/Compilers \
Src/BaseSw/Service/CpuGeneric/If \
Src/BaseSw/Service/CpuGeneric/StdIf \
Src/BaseSw/Service/CpuGeneric/SysSe/Bsp \
Src/BaseSw/Service/CpuGeneric/SysSe/Comm \
Src/BaseSw/Service/CpuGeneric/SysSe/General \
Src/BaseSw/Service/CpuGeneric/SysSe/Math \
Src/BaseSw/Service/CpuGeneric/SysSe/Time \
Src/BaseSw/iLLD/TC26B/Tricore/Asclin/Asc \
Src/BaseSw/iLLD/TC26B/Tricore/Asclin/Lin \
Src/BaseSw/iLLD/TC26B/Tricore/Asclin/Spi \
Src/BaseSw/iLLD/TC26B/Tricore/Asclin/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/Icu \
Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/PwmBc \
Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/PwmHl \
Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/TPwm \
Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/Timer \
Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/TimerWithTrigger \
Src/BaseSw/iLLD/TC26B/Tricore/Cif/Cam \
Src/BaseSw/iLLD/TC26B/Tricore/Cif/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Cpu/CStart \
Src/BaseSw/iLLD/TC26B/Tricore/Cpu/Irq \
Src/BaseSw/iLLD/TC26B/Tricore/Cpu/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Cpu/Trap \
Src/BaseSw/iLLD/TC26B/Tricore/Dma/Dma \
Src/BaseSw/iLLD/TC26B/Tricore/Dma/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Dsadc/Dsadc \
Src/BaseSw/iLLD/TC26B/Tricore/Dsadc/Rdc \
Src/BaseSw/iLLD/TC26B/Tricore/Dsadc/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Dts/Dts \
Src/BaseSw/iLLD/TC26B/Tricore/Dts/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Emem/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Eray/Eray \
Src/BaseSw/iLLD/TC26B/Tricore/Eray/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Fce/Crc \
Src/BaseSw/iLLD/TC26B/Tricore/Fce/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Fft/Fft \
Src/BaseSw/iLLD/TC26B/Tricore/Fft/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Flash/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Gpt12/IncrEnc \
Src/BaseSw/iLLD/TC26B/Tricore/Gpt12/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Atom/Pwm \
Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Atom/PwmHl \
Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Atom/Timer \
Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Tim/In \
Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Tom/Pwm \
Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Tom/PwmHl \
Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Tom/Timer \
Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Trig \
Src/BaseSw/iLLD/TC26B/Tricore/Hssl/Hssl \
Src/BaseSw/iLLD/TC26B/Tricore/Hssl/Std \
Src/BaseSw/iLLD/TC26B/Tricore/I2c/I2c \
Src/BaseSw/iLLD/TC26B/Tricore/I2c/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Iom/Driver \
Src/BaseSw/iLLD/TC26B/Tricore/Iom/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Msc/Msc \
Src/BaseSw/iLLD/TC26B/Tricore/Msc/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Mtu/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Multican/Can \
Src/BaseSw/iLLD/TC26B/Tricore/Multican/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Port/Io \
Src/BaseSw/iLLD/TC26B/Tricore/Port/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Psi5/Psi5 \
Src/BaseSw/iLLD/TC26B/Tricore/Psi5/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Psi5s/Psi5s \
Src/BaseSw/iLLD/TC26B/Tricore/Psi5s/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Qspi/SpiMaster \
Src/BaseSw/iLLD/TC26B/Tricore/Qspi/SpiSlave \
Src/BaseSw/iLLD/TC26B/Tricore/Qspi/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Scu/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Sent/Sent \
Src/BaseSw/iLLD/TC26B/Tricore/Sent/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Smu/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Src/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Stm/Std \
Src/BaseSw/iLLD/TC26B/Tricore/Stm/Timer \
Src/BaseSw/iLLD/TC26B/Tricore/Vadc/Adc \
Src/BaseSw/iLLD/TC26B/Tricore/Vadc/Std \
Src/BaseSw/iLLD/TC26B/Tricore/_Impl \
Src/BaseSw/iLLD/TC26B/Tricore/_Lib/DataHandling \
Src/BaseSw/iLLD/TC26B/Tricore/_Lib/InternalMux \
Src/BaseSw/iLLD/TC26B/Tricore/_PinMap \

